#configuration de la db mongo
data:
  mongodb:
    host: localhost
    port: 27017
    database: teamsmanager
mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

logging:
  level:
    org: WARN
    fr: TRACE


